### ISSUE TITLE
Basic AboutMe section

### ISSUE THREAD

**Issue by Paskanas** [front-end-by-rimantas/35-grupe-portfolio-personal#7]
- [x] sm sceen:
   - [x] img, text, link = block
- [x] md screen & lg screen 
   - [x] 2 columns - img 1/2 & text 1/2

**Comment by krikri89** [comment]
- [ ] sm sceen:
   - [ ] img, h2, h1, link = block
- [ ] md screen 
 - 3 lines of
   - [ ] about me h2
   - [ ] 2 columns - img 1/2 & p 1/2
   - [ ] link 1/2
 - [ ] lg screen 
    - [ ] 2 columns: img & text

**Comment by Paskanas** [comment]
All good :)
